app:
  name: quiz-agent
  icon:
  title: Quiz AI智能助手
  description: 生题、判分。
  author: weizuxiao
  version: 0.0.1

database:
  mongo: mongodb://root:P%40ssw0rd@localhost:27017

llm:
  api-key: sk-cf94911766c24254940c2b6aa140fcf7
  model: qwen-plus
