apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-agent
  labels:
    app: quiz-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-agent
  template:
    metadata:
      labels:
        app: quiz-agent
    spec:
      containers:
      - name: quiz-agent
        image: quiz-agent:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-agent-service
spec:
  selector:
    app: quiz-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quiz-agent-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /quiz-agent
        pathType: Prefix
        backend:
          service:
            name: quiz-agent-service
            port:
              number: 80
